import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainerStyle: {
    paddingTop: 0,
    paddingBottom: 30,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e8eced",
    borderBottomWidth: 1,
    borderColor: "#75797a",
    height: 55,
  },
  headerText: {
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 5,
  },
  newAddress: {
    backgroundColor: "#fff",
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    marginLeft: 15,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: "#22c1f4",
    borderRadius: 20,
  },
  newAddressText: {
    marginLeft: 10,
    fontWeight: 500,
    fontSize: 16,
    color: "#22c1f4",
  },
  addImg: {
    borderWidth: 1,
    borderColor: "#22c1f4",
    borderRadius: 20,
    padding: 3,
    color: "#22c1f4",
  },
  headerButton: {
    position: "absolute",
    left: 10,
  },
  addressPart: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#75797a",
    justifyContent: "space-between",
    borderRadius: 10,
    margin: 15,
    padding: 10,
    backgroundColor: "#fff",
  },
  addressName: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
  },
  addressNameText: {
    fontSize: 18,
    marginLeft: 8,
    fontWeight: 500,
  },
  addressEdit: {
    marginLeft: 30,
    marginRight: 20,
    justifyContent: "space-between",
    borderLeftWidth: 1,
    borderColor: "#75797a",
    paddingLeft: 15,
    marginRight: 6,
  },
});