import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainerStyle: {
    paddingTop: 0,
    paddingBottom: 90,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e8eced",
    borderBottomWidth: 1,
    borderColor: "#75797a",
    height: 55,
  },
  headerText: {
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 5,
    color: "#0aa222",
  },
  headerButton: {
    position: "absolute",
    left: 10,
  },
  address: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#75797a",
    padding: 5,
    marginTop: 30,
  },
  addressTitle: {
    fontWeight: "bold",
    fontSize: 18,
  },
  addressInfo: {
    borderWidth: 1,
    borderColor: "#75797a",
    padding: 5,
    borderRadius: 10,
    margin: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  deliveryName: {
    fontWeight: "bold",
    fontSize: 16,
  },
  addressButtons: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  addressEdit: {
    color: "#22c1f4",
    fontWeight: 500,
  },
  edit: {
    marginRight: 5,
  },
  checkSection: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 40,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  check: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#75797a",
    marginRight: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  pricePanel: {
    bottom: 60,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#e8eced",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: "#75797a",
    paddingHorizontal: 15,
  },
  priceText: {
    fontSize: 20,
    fontWeight: "bold",
  },
  priceButton: {
    backgroundColor: "#22c1f4",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  priceButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
  modalContainer: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderColor: "#75797a",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    marginTop: 10,
  },
  modalItem: {
    padding: 15,
    backgroundColor: '#fff',
    marginVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#75797a",
    width: '80%',
  },
  modalCloseButton: {
    marginVertical: 20,
    padding: 10,
    backgroundColor: "#22c1f4",
    borderRadius: 5,
  },
  modalCloseButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end', 
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
});