import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainerStyle: {
    paddingTop: 0,
    paddingBottom: 90,
  },
  inputs: {
    backgroundColor: "#fff",
    fontSize: 16,
    borderWidth: 1,
    marginBottom: 10,
    padding: 5,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderColor: "#75797a",
    minWidth: "90%",
    maxWidth: "90%",
    marginVertical: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e8eced",
    borderBottomWidth: 1,
    borderColor: "#75797a",
    height: 55,
  },
  headerButton: {
    position: "absolute",
    left: 10,
  },
  headerText: {
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 5,
  },
  addressPart: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#75797a",
    justifyContent: "space-between",
    borderRadius: 10,
    margin: 15,
    padding: 10,
    backgroundColor: "#fff",
  },
  addressName: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    marginBottom: 20,
  },
  addressNameText: {
    fontSize: 18,
    marginLeft: 8,
    fontWeight: 500,
  },
  addressEdit: {
    marginLeft: 30,
    marginRight: 20,
    justifyContent: "space-between",
    borderLeftWidth: 1,
    borderColor: "#75797a",
    paddingLeft: 15,
    marginRight: 6,
  },
  imgContainer: {
    borderBottomWidth: 1,
    borderColor: "#75797a",
    height: 480,
  },
  img: {
    width: "100%",
    resizeMode: "cover",
    height: 479,
  },
  pricePanel: {
    bottom: 60,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#e8eced",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: "#75797a",
    paddingHorizontal: 15,
    height: 70,
  },
  priceText: {
    fontSize: 20,
    fontWeight: "bold",
  },
  priceButton: {
    backgroundColor: "#22c1f4",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  priceButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
  imgNum: {
    color: "#fff",
  },
  imgNumContainer: {
    position: "relative",
    bottom: 35,
    left: 10,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 10,
    alignItems: "center",
    width: 30,
    zIndex: 99,
    padding: 3,
  },
  productInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#75797a",
    paddingHorizontal: 10,
    paddingVertical: 20,
    marginVertical: 10,
    backgroundColor: "#fff",
  },
  brand: {
    fontSize: 18,
    fontWeight: 500,
    color: "#22c1f4",
    marginRight: 5,
  },
  brandText: {
    fontSize: 18,
  },
  infoContainer: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#75797a",
    marginLeft: 20,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
  },
  ratingNum: {
    backgroundColor: "#e8eced",
    padding: 5,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  brandContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  commentContainer: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#75797a",
    width: "90%",
    marginTop: 20,
  },
  commentText: {
    fontSize: 17,
  },
  commentInfoContainer: {
    marginRight: 15,
    marginBottom: 15,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  comment: {
    fontSize: 16,
  },
  commentInfo: {
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#75797a",
    marginVertical: 10,
    backgroundColor: "#fff",
    paddingVertical: 20,
  },
  makeComment: {
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    borderColor: "#75797a",
    paddingBottom: 20,
  }
});